openapi: 3.0.3
info:
  title: Credit card payment api
  description: API to retrieve status of the credit card payment
  version: 1.0.0
servers:
  - url: http://localhost:9090/host/credit-card-payment-api
paths:
  /payment-status:
    post:
      summary: retrieve payment status
      description: Accepts payment reference and provides the status of the payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentStatusRetrievalRequest'
      responses:
        '200':
          description: Successful response with payment status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentStatusResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: Payment not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: Internal server error
components:
  schemas:
    PaymentStatusRetrievalRequest:
      type: object
      properties:
        paymentReference:
          type: string
          description: reference of the payment
          example: DL123456789
      required:
        - paymentReference
    PaymentStatusResponse:
      type: object
      properties:
        lastUpdateDate:
          type: string
          description: last updated at
          format: datetime
          example: 2017-07-21T17:32:28Z
        status:
          type: string
          format: enum
            - CONFIRMED
            - REJECTED
          example: CONFIRMED
          description: Expiry date of the driving license

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message